# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\mainwindow_v2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1075, 778)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/favicon-32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("font-size: 17px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.plainTextInputWords = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextInputWords.setMinimumSize(QtCore.QSize(256, 500))
        self.plainTextInputWords.setMaximumSize(QtCore.QSize(500, 16777215))
        self.plainTextInputWords.setObjectName("plainTextInputWords")
        self.verticalLayout.addWidget(self.plainTextInputWords)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setEnabled(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.tableWidgetResult = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetResult.setMinimumSize(QtCore.QSize(789, 0))
        self.tableWidgetResult.setStyleSheet("QTableWidget {font-size: 13px;}\n"
"QHeaderView::section {\n"
"background-color:#f6f6f6;\n"
"border: 1px solid lightgray;\n"
"}")
        self.tableWidgetResult.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidgetResult.setAlternatingRowColors(True)
        self.tableWidgetResult.setRowCount(20)
        self.tableWidgetResult.setObjectName("tableWidgetResult")
        self.tableWidgetResult.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResult.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResult.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResult.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResult.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResult.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResult.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResult.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResult.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResult.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResult.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResult.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResult.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResult.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResult.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResult.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResult.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetResult.setItem(1, 4, item)
        self.tableWidgetResult.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.tableWidgetResult)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.plainTextEditLog = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEditLog.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEditLog.sizePolicy().hasHeightForWidth())
        self.plainTextEditLog.setSizePolicy(sizePolicy)
        self.plainTextEditLog.setMinimumSize(QtCore.QSize(600, 100))
        self.plainTextEditLog.setMaximumSize(QtCore.QSize(16777215, 110))
        self.plainTextEditLog.setReadOnly(True)
        self.plainTextEditLog.setPlaceholderText("")
        self.plainTextEditLog.setObjectName("plainTextEditLog")
        self.verticalLayout_2.addWidget(self.plainTextEditLog)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 131))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBoxTranslate = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxTranslate.setObjectName("checkBoxTranslate")
        self.verticalLayout_4.addWidget(self.checkBoxTranslate)
        self.checkBoxDefinitions = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxDefinitions.setObjectName("checkBoxDefinitions")
        self.verticalLayout_4.addWidget(self.checkBoxDefinitions)
        self.checkBoxSynonyms = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxSynonyms.setObjectName("checkBoxSynonyms")
        self.verticalLayout_4.addWidget(self.checkBoxSynonyms)
        self.checkBoxAntonyms = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxAntonyms.setObjectName("checkBoxAntonyms")
        self.verticalLayout_4.addWidget(self.checkBoxAntonyms)
        self.horizontalLayout.addWidget(self.groupBox)
        self.pushButtonFind = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonFind.sizePolicy().hasHeightForWidth())
        self.pushButtonFind.setSizePolicy(sizePolicy)
        self.pushButtonFind.setMinimumSize(QtCore.QSize(110, 40))
        self.pushButtonFind.setObjectName("pushButtonFind")
        self.horizontalLayout.addWidget(self.pushButtonFind)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1075, 29))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionRunSettings = QtWidgets.QAction(MainWindow)
        self.actionRunSettings.setObjectName("actionRunSettings")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menu.addAction(self.actionSaveAs)
        self.menu.addSeparator()
        self.menu.addAction(self.actionExit)
        self.menu_2.addAction(self.actionRunSettings)
        self.menu_3.addAction(self.actionAbout)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.label.setBuddy(self.plainTextInputWords)
        self.label_3.setBuddy(self.tableWidgetResult)
        self.label_2.setBuddy(self.plainTextEditLog)

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close)
        self.pushButtonFind.clicked.connect(self.plainTextEditLog.clear)
        self.pushButtonFind.clicked.connect(self.progressBar.reset)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.plainTextInputWords, self.tableWidgetResult)
        MainWindow.setTabOrder(self.tableWidgetResult, self.plainTextEditLog)
        MainWindow.setTabOrder(self.plainTextEditLog, self.checkBoxTranslate)
        MainWindow.setTabOrder(self.checkBoxTranslate, self.checkBoxDefinitions)
        MainWindow.setTabOrder(self.checkBoxDefinitions, self.checkBoxSynonyms)
        MainWindow.setTabOrder(self.checkBoxSynonyms, self.checkBoxAntonyms)
        MainWindow.setTabOrder(self.checkBoxAntonyms, self.pushButtonFind)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tranlsator Desktop - v.3.0"))
        self.label.setText(_translate("MainWindow", "Слова для перевода:"))
        self.plainTextInputWords.setPlaceholderText(_translate("MainWindow", "Введите слова для перевода..."))
        self.label_3.setText(_translate("MainWindow", "Результат:"))
        item = self.tableWidgetResult.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidgetResult.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidgetResult.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Слово"))
        item = self.tableWidgetResult.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Перевод"))
        item = self.tableWidgetResult.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Синонимы"))
        item = self.tableWidgetResult.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Антонимы"))
        item = self.tableWidgetResult.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Определения"))
        __sortingEnabled = self.tableWidgetResult.isSortingEnabled()
        self.tableWidgetResult.setSortingEnabled(False)
        item = self.tableWidgetResult.item(0, 0)
        item.setText(_translate("MainWindow", "Word"))
        item = self.tableWidgetResult.item(0, 1)
        item.setText(_translate("MainWindow", "Word"))
        item = self.tableWidgetResult.item(0, 2)
        item.setText(_translate("MainWindow", "word\\nqwer"))
        item = self.tableWidgetResult.item(0, 4)
        item.setText(_translate("MainWindow", "qweasdfssssssssssssssssssssssssssssssssssssssssssssssssssfasdfasdfasdfasdf"))
        item = self.tableWidgetResult.item(1, 0)
        item.setText(_translate("MainWindow", "adsfasdf"))
        item = self.tableWidgetResult.item(1, 1)
        item.setText(_translate("MainWindow", "asdf"))
        item = self.tableWidgetResult.item(1, 2)
        item.setText(_translate("MainWindow", "asdfasdfasd"))
        item = self.tableWidgetResult.item(1, 3)
        item.setText(_translate("MainWindow", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaa"))
        item = self.tableWidgetResult.item(1, 4)
        item.setText(_translate("MainWindow", "dfasdfdsdfasdfdsdfasdfdsdfasdfdsdfasdfdsdfasdfdsdfasdfdsdfasdfdsdfasdfdsdfasdfds"))
        self.tableWidgetResult.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("MainWindow", "Лог событий:"))
        self.groupBox.setTitle(_translate("MainWindow", "Параметры:"))
        self.checkBoxTranslate.setText(_translate("MainWindow", "Перевод"))
        self.checkBoxDefinitions.setText(_translate("MainWindow", "Определения"))
        self.checkBoxSynonyms.setText(_translate("MainWindow", "Синонимы"))
        self.checkBoxAntonyms.setText(_translate("MainWindow", "Антонимы"))
        self.pushButtonFind.setText(_translate("MainWindow", "Найти"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Инструменты"))
        self.menu_3.setTitle(_translate("MainWindow", "Справка"))
        self.actionSaveAs.setText(_translate("MainWindow", "Сохранить как..."))
        self.actionSaveAs.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionExit.setText(_translate("MainWindow", "Выход"))
        self.actionRunSettings.setText(_translate("MainWindow", "Настройки"))
        self.actionAbout.setText(_translate("MainWindow", "О программе"))

from . import resources
