# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogSettings(object):
    def setupUi(self, DialogSettings):
        DialogSettings.setObjectName("DialogSettings")
        DialogSettings.setWindowModality(QtCore.Qt.WindowModal)
        DialogSettings.resize(560, 231)
        DialogSettings.setMinimumSize(QtCore.QSize(560, 0))
        DialogSettings.setModal(True)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(DialogSettings)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tabWidget = QtWidgets.QTabWidget(DialogSettings)
        self.tabWidget.setObjectName("tabWidget")
        self.tabGeneral = QtWidgets.QWidget()
        self.tabGeneral.setObjectName("tabGeneral")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tabGeneral)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tabGeneral)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEditAppId = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditAppId.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEditAppId.setObjectName("lineEditAppId")
        self.horizontalLayout.addWidget(self.lineEditAppId)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_15.addWidget(self.label_2)
        self.lineEditAppKey = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditAppKey.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEditAppKey.setObjectName("lineEditAppKey")
        self.horizontalLayout_15.addWidget(self.lineEditAppKey)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabGeneral)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.spinBoxOutSynCount = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBoxOutSynCount.setMinimumSize(QtCore.QSize(50, 0))
        self.spinBoxOutSynCount.setMinimum(1)
        self.spinBoxOutSynCount.setMaximum(20)
        self.spinBoxOutSynCount.setObjectName("spinBoxOutSynCount")
        self.verticalLayout_4.addWidget(self.spinBoxOutSynCount)
        self.spinBoxOutAntCount = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBoxOutAntCount.setMinimumSize(QtCore.QSize(50, 0))
        self.spinBoxOutAntCount.setMinimum(1)
        self.spinBoxOutAntCount.setMaximum(20)
        self.spinBoxOutAntCount.setObjectName("spinBoxOutAntCount")
        self.verticalLayout_4.addWidget(self.spinBoxOutAntCount)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 44, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.tabWidget.addTab(self.tabGeneral, "")
        self.tabAdvanced = QtWidgets.QWidget()
        self.tabAdvanced.setObjectName("tabAdvanced")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tabAdvanced)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tabAdvanced)
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_5)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.spinBoxRequestTimeout = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBoxRequestTimeout.setMinimum(1)
        self.spinBoxRequestTimeout.setObjectName("spinBoxRequestTimeout")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBoxRequestTimeout)
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.spinBoxRequestInterval = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBoxRequestInterval.setMinimum(1)
        self.spinBoxRequestInterval.setMaximum(5)
        self.spinBoxRequestInterval.setObjectName("spinBoxRequestInterval")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBoxRequestInterval)
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tabAdvanced)
        self.groupBox_6.setObjectName("groupBox_6")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_6)
        self.formLayout.setObjectName("formLayout")
        self.label_14 = QtWidgets.QLabel(self.groupBox_6)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.spinBoxSaveCategoryCount = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBoxSaveCategoryCount.setObjectName("spinBoxSaveCategoryCount")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBoxSaveCategoryCount)
        self.label_15 = QtWidgets.QLabel(self.groupBox_6)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.spinBoxSaveItemsCount = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinBoxSaveItemsCount.setObjectName("spinBoxSaveItemsCount")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBoxSaveItemsCount)
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.groupBox_6)
        self.verticalLayout_7.addLayout(self.formLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.tabWidget.addTab(self.tabAdvanced, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.fontComboBox = QtWidgets.QFontComboBox(self.groupBox_3)
        self.fontComboBox.setObjectName("fontComboBox")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fontComboBox)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.sizeComboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.sizeComboBox.setEditable(True)
        self.sizeComboBox.setMaxVisibleItems(10)
        self.sizeComboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.sizeComboBox.setObjectName("sizeComboBox")
        self.sizeComboBox.addItem("")
        self.sizeComboBox.addItem("")
        self.sizeComboBox.addItem("")
        self.sizeComboBox.addItem("")
        self.sizeComboBox.addItem("")
        self.sizeComboBox.addItem("")
        self.sizeComboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.sizeComboBox)
        self.formLayout_4.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.intervalComboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.intervalComboBox.setObjectName("intervalComboBox")
        self.intervalComboBox.addItem("")
        self.intervalComboBox.addItem("")
        self.intervalComboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.intervalComboBox)
        self.formLayout_4.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.horizontalLayout_6.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.doubleSpinBoxMarginTop = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBoxMarginTop.setDecimals(1)
        self.doubleSpinBoxMarginTop.setMinimum(1.0)
        self.doubleSpinBoxMarginTop.setMaximum(3.0)
        self.doubleSpinBoxMarginTop.setSingleStep(0.1)
        self.doubleSpinBoxMarginTop.setObjectName("doubleSpinBoxMarginTop")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxMarginTop)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.doubleSpinBoxMarginRight = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBoxMarginRight.setDecimals(1)
        self.doubleSpinBoxMarginRight.setMinimum(1.0)
        self.doubleSpinBoxMarginRight.setMaximum(3.0)
        self.doubleSpinBoxMarginRight.setSingleStep(0.1)
        self.doubleSpinBoxMarginRight.setObjectName("doubleSpinBoxMarginRight")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxMarginRight)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.doubleSpinBoxMarginBottom = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBoxMarginBottom.setDecimals(1)
        self.doubleSpinBoxMarginBottom.setMinimum(1.0)
        self.doubleSpinBoxMarginBottom.setMaximum(3.0)
        self.doubleSpinBoxMarginBottom.setSingleStep(0.1)
        self.doubleSpinBoxMarginBottom.setObjectName("doubleSpinBoxMarginBottom")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxMarginBottom)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.doubleSpinBoxMarginLeft = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBoxMarginLeft.setDecimals(1)
        self.doubleSpinBoxMarginLeft.setMinimum(1.0)
        self.doubleSpinBoxMarginLeft.setMaximum(3.0)
        self.doubleSpinBoxMarginLeft.setSingleStep(0.1)
        self.doubleSpinBoxMarginLeft.setObjectName("doubleSpinBoxMarginLeft")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxMarginLeft)
        self.horizontalLayout_6.addWidget(self.groupBox_4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem4 = QtWidgets.QSpacerItem(20, 123, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_9.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogSettings)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_9.addWidget(self.buttonBox)

        self.retranslateUi(DialogSettings)
        self.tabWidget.setCurrentIndex(2)
        self.sizeComboBox.setCurrentIndex(0)
        self.buttonBox.accepted.connect(DialogSettings.accept)
        self.buttonBox.rejected.connect(DialogSettings.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogSettings)

    def retranslateUi(self, DialogSettings):
        _translate = QtCore.QCoreApplication.translate
        DialogSettings.setWindowTitle(_translate("DialogSettings", "Настройки"))
        self.groupBox.setTitle(_translate("DialogSettings", "Приложение"))
        self.label.setText(_translate("DialogSettings", "Application ID:"))
        self.label_2.setText(_translate("DialogSettings", "Application Key:"))
        self.groupBox_2.setTitle(_translate("DialogSettings", "Выходные данные"))
        self.label_3.setText(_translate("DialogSettings", "Количество синонимов:"))
        self.label_4.setText(_translate("DialogSettings", "Количество антонимов:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGeneral), _translate("DialogSettings", "Общие"))
        self.groupBox_5.setTitle(_translate("DialogSettings", "Запросы"))
        self.label_12.setText(_translate("DialogSettings", "Время ожидания:"))
        self.label_13.setText(_translate("DialogSettings", "Интервал запросов:"))
        self.groupBox_6.setTitle(_translate("DialogSettings", "База данных"))
        self.label_14.setText(_translate("DialogSettings", "Категорий для сохранения:"))
        self.label_15.setText(_translate("DialogSettings", "Элементов для сохранения:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAdvanced), _translate("DialogSettings", "Системные"))
        self.groupBox_3.setTitle(_translate("DialogSettings", "Шрифт и абзац"))
        self.label_5.setText(_translate("DialogSettings", "Шрифт:"))
        self.label_6.setText(_translate("DialogSettings", "Размер:"))
        self.sizeComboBox.setItemText(0, _translate("DialogSettings", "8"))
        self.sizeComboBox.setItemText(1, _translate("DialogSettings", "9"))
        self.sizeComboBox.setItemText(2, _translate("DialogSettings", "10"))
        self.sizeComboBox.setItemText(3, _translate("DialogSettings", "11"))
        self.sizeComboBox.setItemText(4, _translate("DialogSettings", "12"))
        self.sizeComboBox.setItemText(5, _translate("DialogSettings", "13"))
        self.sizeComboBox.setItemText(6, _translate("DialogSettings", "14"))
        self.label_7.setText(_translate("DialogSettings", "Интервал:"))
        self.intervalComboBox.setItemText(0, _translate("DialogSettings", "1.0"))
        self.intervalComboBox.setItemText(1, _translate("DialogSettings", "1.15"))
        self.intervalComboBox.setItemText(2, _translate("DialogSettings", "1.5"))
        self.groupBox_4.setTitle(_translate("DialogSettings", "Поля страницы"))
        self.label_8.setText(_translate("DialogSettings", "Верхнее:"))
        self.label_11.setText(_translate("DialogSettings", "Правое:"))
        self.label_10.setText(_translate("DialogSettings", "Нижнее:"))
        self.label_9.setText(_translate("DialogSettings", "Левое:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DialogSettings", "MS Word"))

